---
version: '3'

services:
  bedsamplot:
    container_name: bedsamplot
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/samplot:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - bedsamplot
